# Generated by Django 5.0 on 2026-05-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Matn')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Rasm (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ko'rsatish tartibi")),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Rasm (URL)')),
                ('prep_time_minutes', models.IntegerField(default=15, verbose_name='Pishirish vaqti (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('waiter', 'Ofitsiant'), ('chef', 'Oshpaz'), ('admin', 'Administrator'), ('cleaner', 'Farrosh')], default='waiter', max_length=20, verbose_name='Lavozim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR kod (URL)')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Stol raqami')),
                ('status', models.CharField(choices=[('free', "Bo'sh"), ('occupied', 'Band'), ('reserved', 'Bron qilingan'), ('cleaning', 'Tozalanmoqda')], default='free', max_length=20, verbose_name='Holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR kod (URL)')),
                ('current_session_start', models.DateTimeField(blank=True, null=True, verbose_name='Joriy sessiya boshlanishi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Taom nomi')),
                ('description', models.TextField(verbose_name='Taom haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'm)")),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='Rasm (URL)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('prep_time_minutes', models.IntegerField(default=20, verbose_name='Tayyorlash vaqti (daqiqa)')),
                ('serving_options', models.JSONField(blank=True, default=list, verbose_name='Porsiya turlari')),
                ('ingredients', models.TextField(blank=True, verbose_name='Tarkibi')),
                ('vitamins', models.CharField(blank=True, max_length=500, verbose_name='Vitaminlar')),
                ('weight_grams', models.IntegerField(default=250, verbose_name="Og'irligi (g)")),
                ('calories', models.IntegerField(default=0, verbose_name='Kaloriya')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'ordering': ['category__order', 'name'],
            },
        ),
    ]
