# Generated by Django 5.0 on 2026-05-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Juda yomon'), (2, '2 - Yomon'), (3, "3 - O'rtacha"), (4, '4 - Yaxshi'), (5, "5 - A'lo")], verbose_name='Baho')),
                ('comment', models.TextField(blank=True, verbose_name='Fikr')),
                ('menu_item_name', models.CharField(blank=True, max_length=200, verbose_name='Taom nomi')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='core.table', verbose_name='Stol')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': 'Fikrlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
