# Generated by Django 5.0 on 2026-05-05 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('preparing', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('delivered', 'Yetkazildi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holat')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Eslatma')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.table', verbose_name='Stol')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Soni')),
                ('servings', models.IntegerField(default=1, verbose_name='Kishilik')),
                ('price_per_serving', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bir kishilik narx')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha")),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.menuitem', verbose_name='Taom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Rad etildi'), ('refunded', 'Qaytarildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='Tranzaksiya ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Chaqirilgan vaqt')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Javob berildi')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob vaqti')),
                ('reply_message', models.TextField(blank=True, verbose_name='Javob xabari')),
                ('staff_phone', models.CharField(blank=True, max_length=20, verbose_name='Xodim telefoni')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiter_calls', to='core.table', verbose_name='Stol')),
            ],
            options={
                'verbose_name': 'Ofitsiant chaqiruvi',
                'verbose_name_plural': 'Ofitsiant chaqiruvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
